version: '3.8'

services:
  serp_worker:
    build: .
    container_name: pc5_worker
    environment:
      - PC_ID=PC5
      - PC1_IP=${PC1_IP}
      - SERP_API_KEY=${SERP_API_KEY}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASS=${RABBITMQ_PASS}
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    restart: unless-stopped
    ports:
      - "8003:8000"  # Different port from other PCs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  business_worker:
    build: .
    environment:
      - SERVICE_TYPE=business
      - RABBITMQ_HOST=172.245.79.115
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=zoeman
      - RABBITMQ_PASSWORD=TestingPurposes9!
      - METRICS_PORT=8005
    volumes:
      - ./src:/app/src
    networks:
      - pc5_network

networks:
  pc5_network:
    driver: bridge