version: '3.8'

services:
  domain_email_worker:
    build: .
    container_name: pc4_domain_email_worker
    environment:
      - PC_ID=PC4
      - PC1_IP=${PC1_IP:-localhost}
      - DOMAIN_API_KEY=${DOMAIN_API_KEY:-}
      - EMAIL_API_KEY=${EMAIL_API_KEY:-}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
      - RABBITMQ_HOST=172.245.79.115
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=zoeman
      - RABBITMQ_PASSWORD=TestingPurposes9!
      - SERVICE_TYPE=domain_email
      - METRICS_PORT=8004
      - PYTHONUNBUFFERED=1
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
      - /app/src/__pycache__
    restart: unless-stopped
    ports:
      - "8004:8004"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8004/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - pc4_network

  leak_check_worker:
    build: .
    container_name: pc4_leak_check_worker
    environment:
      - PC_ID=PC4_LEAK
      - PC1_IP=${PC1_IP:-localhost}
      - DEHASHED_API_KEY=${DEHASHED_API_KEY:-}
      - LEAKCHECK_API_KEY=${LEAKCHECK_API_KEY:-}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-redis}
      - RABBITMQ_HOST=172.245.79.115
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=zoeman
      - RABBITMQ_PASSWORD=TestingPurposes9!
      - SERVICE_TYPE=leak_check
      - METRICS_PORT=8003
    volumes:
      - ./src:/app/src
      - ./logs:/app/logs
    restart: unless-stopped
    ports:
      - "8003:8003"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/metrics"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      - domain_email_worker
    networks:
      - pc4_network

networks:
  pc4_network:
    driver: bridge