global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']

  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']

  - job_name: 'business_workers'
    static_configs:
      - targets: ['pc2:8000', 'pc3:8000']

  - job_name: 'domain_email_worker'
    static_configs:
      - targets: ['pc4:8000']

  - job_name: 'serp_worker'
    static_configs:
      - targets: ['pc5:8000']